### ISSUE TITLE
[comment] 简直是疯了

### ISSUE THREAD

**Issue by L0891-3BDBFF** [Skiawm91/OneOS#2]
在github你甚至可以看见有人用批处理写OS in OS（虽然早停更了）
脚本复杂度震惊我一万年

**Comment by Skiawm91** [comment]
1. 這就是批處理啊
2. 這東西其實不複雜，都是些簡單的指令而已

**Comment by L0891-3BDBFF** [comment]
可能这就是当局者清旁观者迷罢
反正我每行代码看得明明白白的合起来就看不是很懂了
